// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwFa_GuRilJCMC29h7KfoZgFdg_FNsuu4',
    appId: '1:376238925135:web:b92687cd8f86babd7a913a',
    messagingSenderId: '376238925135',
    projectId: 'fir-emailandpass',
    authDomain: 'fir-emailandpass.firebaseapp.com',
    storageBucket: 'fir-emailandpass.appspot.com',
    measurementId: 'G-B54JPMFQSR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb31tFDeyIokS7ZS_qI8L0AtxiG98rs8I',
    appId: '1:376238925135:android:66fad5b5a085b5bd7a913a',
    messagingSenderId: '376238925135',
    projectId: 'fir-emailandpass',
    storageBucket: 'fir-emailandpass.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkg08VKoMNb222mAbn8OtJbXg4k50eurw',
    appId: '1:376238925135:ios:82d735d0174cff707a913a',
    messagingSenderId: '376238925135',
    projectId: 'fir-emailandpass',
    storageBucket: 'fir-emailandpass.appspot.com',
    iosClientId: '376238925135-ruhqv4vcaijdnl4hdm04dvbo0vsv5ci0.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthEmail',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkg08VKoMNb222mAbn8OtJbXg4k50eurw',
    appId: '1:376238925135:ios:82d735d0174cff707a913a',
    messagingSenderId: '376238925135',
    projectId: 'fir-emailandpass',
    storageBucket: 'fir-emailandpass.appspot.com',
    iosClientId: '376238925135-ruhqv4vcaijdnl4hdm04dvbo0vsv5ci0.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthEmail',
  );
}
